-- ==============================================
-- TRIPWIRE DATABASE MIGRATION SCHEMA
-- ==============================================
-- Этот скрипт создает все необходимые таблицы для Tripwire в НОВОЙ базе данных
-- Выполняется ОДИН РАЗ при настройке нового Supabase проекта

-- ==============================================
-- 1. ТАБЛИЦА COURSES
-- ==============================================
CREATE TABLE IF NOT EXISTS public.courses (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  thumbnail_url TEXT,
  order_index INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT FALSE,
  is_archived BOOLEAN DEFAULT FALSE,
  total_xp INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.courses IS 'Курсы платформы Tripwire';

-- ==============================================
-- 2. ТАБЛИЦА MODULES
-- ==============================================
CREATE TABLE IF NOT EXISTS public.modules (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER REFERENCES public.courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  order_index INTEGER DEFAULT 0,
  is_archived BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.modules IS 'Модули курсов Tripwire';

-- ==============================================
-- 3. ТАБЛИЦА LESSONS
-- ==============================================
CREATE TABLE IF NOT EXISTS public.lessons (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  module_id INTEGER REFERENCES public.modules(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  tip TEXT,
  ai_description TEXT,
  ai_tips TEXT,
  video_url TEXT,
  bunny_video_id TEXT,
  duration_minutes INTEGER DEFAULT 0,
  lesson_type VARCHAR CHECK (lesson_type IN ('video', 'text', 'quiz', 'assignment')) DEFAULT 'video',
  xp_reward INTEGER DEFAULT 10,
  order_index INTEGER DEFAULT 0,
  is_preview BOOLEAN DEFAULT FALSE,
  is_archived BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.lessons IS 'Уроки Tripwire курса';

-- ==============================================
-- 4. ТАБЛИЦА USERS (базовая, для auth.users)
-- ==============================================
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE,
  full_name TEXT,
  role TEXT DEFAULT 'student' CHECK (role IN ('student', 'admin', 'sales')),
  platform TEXT DEFAULT 'tripwire' CHECK (platform IN ('main', 'tripwire')),
  total_xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.users IS 'Пользователи Tripwire (отдельная БД)';
COMMENT ON COLUMN public.users.platform IS 'Всегда tripwire в этой базе';

-- ==============================================
-- 5. ТАБЛИЦА TRIPWIRE_USERS
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  granted_by UUID NOT NULL, -- ID менеджера, который создал аккаунт (может быть из другой БД)
  manager_name TEXT,
  generated_password TEXT NOT NULL,
  password_changed BOOLEAN DEFAULT FALSE,
  welcome_email_sent BOOLEAN DEFAULT FALSE,
  welcome_email_sent_at TIMESTAMPTZ,
  email_opened BOOLEAN DEFAULT FALSE,
  first_login_at TIMESTAMPTZ,
  last_active_at TIMESTAMPTZ,
  modules_completed INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'completed', 'blocked')),
  amocrm_deal_id TEXT,
  amocrm_contact_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.tripwire_users IS 'Метаданные пользователей Tripwire (созданных Sales Manager)';

-- ==============================================
-- 6. ТАБЛИЦА TRIPWIRE_USER_PROFILE
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_user_profile (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  modules_completed INTEGER DEFAULT 0 CHECK (modules_completed >= 0 AND modules_completed <= 3),
  total_modules INTEGER DEFAULT 3,
  completion_percentage NUMERIC DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  certificate_issued BOOLEAN DEFAULT FALSE,
  certificate_url TEXT,
  certificate_issued_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.tripwire_user_profile IS 'Профили пользователей Tripwire: прогресс, сертификаты';

-- ==============================================
-- 7. ТАБЛИЦА TRIPWIRE_PROGRESS
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tripwire_user_id TEXT NOT NULL, -- Может быть UUID (для авторизованных) или localStorage ID (для гостей)
  lesson_id INTEGER NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
  is_completed BOOLEAN DEFAULT FALSE,
  video_progress_percent INTEGER DEFAULT 0 CHECK (video_progress_percent >= 0 AND video_progress_percent <= 100),
  last_position_seconds INTEGER DEFAULT 0,
  watch_time_seconds INTEGER DEFAULT 0,
  watched_segments JSONB DEFAULT '[]'::JSONB,
  total_watched_seconds INTEGER DEFAULT 0,
  video_duration INTEGER DEFAULT 0,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(tripwire_user_id, lesson_id)
);

COMMENT ON TABLE public.tripwire_progress IS 'Прогресс пользователей по урокам Tripwire';

-- ==============================================
-- 8. ТАБЛИЦА TRIPWIRE_ACHIEVEMENTS
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_achievements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  achievement_type TEXT NOT NULL CHECK (achievement_type IN ('module_1_completed', 'module_2_completed', 'module_3_completed')),
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  unlocked BOOLEAN DEFAULT FALSE,
  unlocked_at TIMESTAMPTZ,
  notification_shown BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, achievement_type)
);

COMMENT ON TABLE public.tripwire_achievements IS 'Достижения пользователей Tripwire (3 достижения за модули)';

-- ==============================================
-- 9. ТАБЛИЦА TRIPWIRE_CERTIFICATES
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  certificate_number TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  course_name TEXT DEFAULT 'Tripwire: Введение в AI',
  certificate_url TEXT NOT NULL,
  issued_at TIMESTAMPTZ DEFAULT NOW(),
  downloaded_at TIMESTAMPTZ,
  download_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.tripwire_certificates IS 'Сертификаты пользователей Tripwire';

-- ==============================================
-- 10. ТАБЛИЦА TRIPWIRE_AI_THREADS
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_ai_threads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assistant_id TEXT,
  thread_id TEXT,
  title TEXT DEFAULT 'Новый диалог',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_message_at TIMESTAMPTZ DEFAULT NOW(),
  message_count INTEGER DEFAULT 0,
  is_archived BOOLEAN DEFAULT FALSE
);

COMMENT ON TABLE public.tripwire_ai_threads IS 'Треды AI-куратора для Tripwire';

-- ==============================================
-- 11. ТАБЛИЦА TRIPWIRE_AI_MESSAGES
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_ai_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id UUID NOT NULL REFERENCES public.tripwire_ai_threads(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT,
  openai_message_id TEXT,
  openai_run_id TEXT,
  has_attachments BOOLEAN DEFAULT FALSE,
  attachment_count INTEGER DEFAULT 0,
  is_voice_message BOOLEAN DEFAULT FALSE,
  transcription_text TEXT,
  response_time_ms INTEGER,
  token_count INTEGER,
  model_used TEXT,
  sentiment TEXT,
  topics TEXT[],
  lesson_reference TEXT,
  lesson_timestamp INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.tripwire_ai_messages IS 'Сообщения AI-куратора Tripwire';

-- ==============================================
-- 12. ТАБЛИЦА TRIPWIRE_AI_ATTACHMENTS
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_ai_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL REFERENCES public.tripwire_ai_messages(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_type TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  openai_file_id TEXT,
  storage_url TEXT,
  thumbnail_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================
-- 13. ТАБЛИЦА TRIPWIRE_AI_COSTS
-- ==============================================
CREATE TABLE IF NOT EXISTS public.tripwire_ai_costs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cost_type VARCHAR NOT NULL, -- 'curator_chat', 'curator_whisper', 'lesson_transcription'
  service VARCHAR NOT NULL,
  model VARCHAR NOT NULL,
  tokens_used INTEGER DEFAULT 0,
  cost_usd NUMERIC NOT NULL,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.tripwire_ai_costs IS 'Трекинг затрат на AI для Tripwire';

-- ==============================================
-- 14. ТАБЛИЦА SALES_ACTIVITY_LOG
-- ==============================================
CREATE TABLE IF NOT EXISTS public.sales_activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  manager_id UUID NOT NULL, -- ID менеджера (может быть из другой БД, поэтому без FK)
  action_type TEXT NOT NULL CHECK (action_type IN ('user_created', 'email_sent', 'status_changed', 'password_reset', 'user_deleted')),
  target_user_id UUID, -- ID пользователя Tripwire (FK к auth.users)
  details JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.sales_activity_log IS 'Логирование действий менеджеров по продажам';

-- ==============================================
-- ИНДЕКСЫ ДЛЯ ПРОИЗВОДИТЕЛЬНОСТИ
-- ==============================================
CREATE INDEX IF NOT EXISTS idx_modules_course_id ON public.modules(course_id);
CREATE INDEX IF NOT EXISTS idx_lessons_module_id ON public.lessons(module_id);
CREATE INDEX IF NOT EXISTS idx_tripwire_progress_user_lesson ON public.tripwire_progress(tripwire_user_id, lesson_id);
CREATE INDEX IF NOT EXISTS idx_tripwire_users_email ON public.tripwire_users(email);
CREATE INDEX IF NOT EXISTS idx_tripwire_ai_threads_user ON public.tripwire_ai_threads(user_id);
CREATE INDEX IF NOT EXISTS idx_tripwire_ai_messages_thread ON public.tripwire_ai_messages(thread_id);

-- ==============================================
-- RLS POLICIES (Row Level Security)
-- ==============================================

-- Courses: публичный доступ на чтение
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Courses are viewable by everyone" ON public.courses FOR SELECT USING (true);

-- Modules: публичный доступ на чтение
ALTER TABLE public.modules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Modules are viewable by everyone" ON public.modules FOR SELECT USING (true);

-- Lessons: публичный доступ на чтение
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lessons are viewable by everyone" ON public.lessons FOR SELECT USING (true);

-- Users: пользователь видит только свою запись
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own data" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own data" ON public.users FOR UPDATE USING (auth.uid() = id);

-- Tripwire Progress: пользователь видит только свой прогресс
ALTER TABLE public.tripwire_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own progress" ON public.tripwire_progress FOR SELECT USING (tripwire_user_id::uuid = auth.uid());
CREATE POLICY "Users can insert own progress" ON public.tripwire_progress FOR INSERT WITH CHECK (tripwire_user_id::uuid = auth.uid());
CREATE POLICY "Users can update own progress" ON public.tripwire_progress FOR UPDATE USING (tripwire_user_id::uuid = auth.uid());

-- Tripwire Profile: пользователь видит только свой профиль
ALTER TABLE public.tripwire_user_profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own profile" ON public.tripwire_user_profile FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users can update own profile" ON public.tripwire_user_profile FOR UPDATE USING (user_id = auth.uid());

-- Tripwire Achievements: пользователь видит только свои достижения
ALTER TABLE public.tripwire_achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own achievements" ON public.tripwire_achievements FOR SELECT USING (user_id = auth.uid());

-- Tripwire Certificates: пользователь видит только свой сертификат
ALTER TABLE public.tripwire_certificates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own certificate" ON public.tripwire_certificates FOR SELECT USING (user_id = auth.uid());

-- Tripwire AI Threads: пользователь видит только свои треды
ALTER TABLE public.tripwire_ai_threads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own threads" ON public.tripwire_ai_threads FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users can insert own threads" ON public.tripwire_ai_threads FOR INSERT WITH CHECK (user_id = auth.uid());

-- Tripwire AI Messages: пользователь видит только свои сообщения
ALTER TABLE public.tripwire_ai_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own messages" ON public.tripwire_ai_messages FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users can insert own messages" ON public.tripwire_ai_messages FOR INSERT WITH CHECK (user_id = auth.uid());

-- ==============================================
-- TRIGGERS (Auto-update updated_at)
-- ==============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_courses_updated_at BEFORE UPDATE ON public.courses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_modules_updated_at BEFORE UPDATE ON public.modules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_lessons_updated_at BEFORE UPDATE ON public.lessons FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_tripwire_users_updated_at BEFORE UPDATE ON public.tripwire_users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_tripwire_user_profile_updated_at BEFORE UPDATE ON public.tripwire_user_profile FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_tripwire_progress_updated_at BEFORE UPDATE ON public.tripwire_progress FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==============================================
-- SCHEMA MIGRATION COMPLETE
-- ==============================================
-- Теперь база готова для миграции данных

